### ISSUE TITLE
Add licensing info

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/logo#2]
We should add licensing info for the logo and for the style guide (and likely all further documentation that we might add to this repo).

For the logo, we would likely need the license approved by @mamarilmanson as the author (it would be nice that the license hands over the copyright to "KOBUGE-Games and contributors" btw, so that we don't have to bother about this later on).
I'd propose CC-BY-SA 4.0, but feel free to propose something else.

For the style guide and potential further documentation, I'd propose CC0.

WDYT?

**Comment by bojidar-bg** [comment]
Just a note, Wikipedia uses CC-BY-SA 3.0 for text.

**Comment by Calinou** [comment]
> Just a note, Wikipedia uses CC-BY-SA 3.0 for text.

It doesn't really matter, as they avoid directly copy-pasting documentation on Wikipedia. So, we _can_ use CC BY-SA 4.0 just fine.

**Comment by est31** [comment]
I don't think logos should be freely licensed. Do you want others to call themselves KOBUGDR and bear the logo (instead of a trabi)?

**Comment by akien-mga** [comment]
> I don't think logos should be freely licensed. Do you want others to call themselves KOBUGDR and bear the logo (instead of a trabi)?

Well I'm positive the logo should _not_ be nonfree. We don't want to include nonfree content in all our games just for the sake of preventing people from reusing it.

Even Godot's logo is CC-BY 3.0: https://github.com/godotengine/godot/blob/master/LOGO_LICENSE.md

Firefox has a nonfree logo, and that's one of the main reasons why there are forks like iceweasel...

**Comment by mamarilmanson** [comment]
uhm... I'm not really familiar with licenses... even though I  read them I might still not understand them...-_-

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ I would try to outline Creative Commons licenses below. ( @Calinou Please, correct me if I'm wrong )

(**Disclaimer: I'm not a lawyer, so I might mispresent facts in such a way that you don't understand them fully. Also, I might myself not understand what I'm talking of, so please, bear with me.**)

| __Name__ | Description |
| --- | --- |
| CC0 | _Public domain, similar to the MIT/expat license for code_. You give everybody permissions to reproduce, remix, share, or otherwise cripple your creation, as long as they don't claim it was "all their work". They can still give credit to you if they want, though. |
| CC BY | Similar to CC0, but this time other people MUST give you credit, whenever they remix, share, etc. Note that they are free to sell remixes. |
| **CC BY-SA** | _Share-alike, quite similar to GPL_. This is all of CC BY, but this time others have to share it under the same license. This is what @akien-mga proposes |
| CC BY-ND | _No derivatives_. This is all of CC BY, but this time others can't remix it or build upon it. |
| CC BY-NC | _Non-commercial_. This is all of CC BY, but this time others can't sell it, or otherwise use it to win money. |
| CC BY-NC-SA | _Non-commercial, Share-alike_. This is simply CC BY-SA and CC BY-NC combined. |
| CC BY-NC-ND | _Non-commercial, No derivatives_. This is simply CC BY-SA and CC BY-ND combined. |

That's all of them up-to-date (AFAIK). Also, make sure to check [the Creative Commons License Chooser](https://creativecommons.org/choose/), as it might help you understand them a bit better.

P.S. @akien-mga also said that you might grant the license's 

> copyright to "KOBUGE-Games and contributors", so that we don't have to bother about this later on

**Comment by mamarilmanson** [comment]
I'm not sure I understood but what my mind tells me is CC BY-NC-ND... what do you think???

**Comment by ObaniGemini** [comment]
Well, non commercial use would forbid, for example YouTube videos with money rent. This is to see

**Comment by Calinou** [comment]
> I'm not sure I understood but what my mind tells me is CC BY-NC-ND... what do you think???

I think you didn't understand it. :suspect:

See [this page](http://freedomdefined.org/Licenses/NC) on why NC is bad.

**Comment by fry-** [comment]
I want my work published in this repo to be **CC BY-SA 4.0 or higher**, and I would like to see ALL the work published here to use the same license :blush:

**Comment by akien-mga** [comment]
I dropped the nonfree logos and updated the README: ab0ff8a
